name: Upload Packages

on:
  push

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Upload minecraft-msftauth package
        run: |
          mvn deploy:deploy-file -Dfile=path/to/minecraft-msftauth-2.1.6.jar -DpomFile=path/to/minecraft-msftauth-2.1.6.pom -DrepositoryId=github -Durl=https://maven.pkg.github.com/OWNER/REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload libmitm package
        run: |
          mvn deploy:deploy-file -Dfile=path/to/libmitm-1.2.3-raknet.aar -DpomFile=path/to/libmitm-1.2.3-raknet.pom -DrepositoryId=github -Durl=https://maven.pkg.github.com/OWNER/REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
