name: Upload Packages

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    env:
      USERNAME_GITHUB: ${{ secrets.GITHUB_USERNAME }}
      TOKEN_GITHUB: ${{ secrets.TOKEN2 }}
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Upload minecraft-msftauth package
        run: |
          mvn deploy:deploy-file -Dfile=coelho.msftauth/minecraft-msftauth/2.1.6/3e97bee0da5e47cf7b7c567e2271a2a57b92bc6e/minecraft-msftauth-2.1.6.jar -DpomFile=coelho.msftauth/minecraft-msftauth/2.1.6/6555743316beda84b92d468c68b5bd101fbf0a87/minecraft-msftauth-2.1.6.pom -DrepositoryId=ProtoHax-PackageGit -Durl=https://maven.pkg.github.com/SkidderMC/ProtoHax-PackageGit
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.TOKEN2 }}
          GITHUB_TOKEN: ${{ secrets.TOKEN2 }}

      - name: Upload libmitm package
        run: |
          mvn deploy:deploy-file -Dfile=dev.sora.networking/libmitm/1.2.3-raknet/ce1b60a4ad10ac9b0610bf5a9774a6c01c60fa58/libmitm-1.2.3-raknet.aar -DpomFile=dev.sora.networking/libmitm/1.2.3-raknet/afce312565aa3b22fc520136edee843ffdf73f20/libmitm-1.2.3-raknet.pom -DrepositoryId=ProtoHax-PackageGit -Durl=https://maven.pkg.github.com/SkidderMC/ProtoHax-PackageGit
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.TOKEN2 }}
          GITHUB_TOKEN: ${{ secrets.TOKEN2 }}
